config/routes.rb
Rails.application.routes.draw do
  resources :games do
    member do
      post 'add_frame'
    end
  end
  resources :frames
  root 'games#new'

end

app/models/frame.rb
class Frame < ActiveRecord::Base
  belongs_to :game
  # attr_accessor :roll1, :roll2, :points, :strike, :spare
  # validates :first_roll, :second_roll, presence: true
  validates :first_roll, numericality: { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10 }
  validates :second_roll, numericality: {:allow_blank => true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10 }
  validate :check_total_score
  before_create :process

  def check_total_score
    if extra_frame
      if (total_score? > 20 || total_score? < 0)
        errors.add(:base, "Total sum cannot be more than 20 or less than 0")
      end
    else
      if total_score? > 10 || total_score? < 0
        errors.add(:base, "Total sum cannot be more than 10 or less than 0")
      end
    end
  end

  def update_and_mark!(score: total_score?)
    self.score = score
    self.mark  = true
    save!
  end

  def process
    if is_strike?
      self.second_roll = nil
    end
    if (!is_strike? && !is_spare?) || extra_frame
      self.score = total_score?
      self.mark = true
    end
  end

  def is_strike?
    return false if extra_frame
    first_roll == 10 && (second_roll.nil? || second_roll == 0)
  end

  def is_spare?
    return false if extra_frame
    !is_strike? && total_score? == 10
  end

  def total_score?
    score = 0
    score += first_roll if first_roll
    score += second_roll if second_roll
    score
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :frames, -> { order "created_at ASC" }

  def finished?
    return false if self.frames.count < 10
    return false if extra_frame?
    true
  end

  # if the 11th frame is required?
  def extra_frame?
    if self.frames.count == 10
      last_frame = frames.last
      return true if last_frame.is_strike? || last_frame.is_spare?
    end
    false
  end

  def final_score?
    update_score
    frames.take(10).map(&:score).inject(:+)
  end

  # loops through the frames created so far
  # updates the score for strike and spare frame
  def update_score
    frames.take(10).each_with_index do |frame, index|
      # do not consider any frame that is already marked done
      # or the extra frame (11th frame)
      # byebug
      unless frame.mark || frame.extra_frame
        # for all frame besides the 10th frame
        if index < 9
          # if frame is strike check for two consequetive ball
          # byebug
          if frame.is_strike? && frames[index.succ]
            next_frame = frames[index.succ]
            if next_frame.is_strike?
              new_index = index.succ
              if frames[new_index.succ]
                next_frame = frames[new_index.succ]
                points = 20 + next_frame.first_roll
                frame.update_and_mark!(score: points)
              end
            else
              points = 10 + next_frame.total_score?
              frame.update_and_mark!(score: points)
            end
          end
          # if frame is spare check for one consequetive ball
          if frame.is_spare? && frames[index.succ]
            points = 10 + frames[index.succ].first_roll
            frame.update_and_mark!(score: points)
          end
        else
          # for the last frame (10th frame)
          if frames[index.succ]
            next_frame = frames[index.succ]
            points = 10 + next_frame.total_score?
            frame.update_and_mark!(score: points)
          end
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :add_frame]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game.update_score
    if @game.finished?
      render 'finished'
    end
    @frame = Frame.new
    if @game.extra_frame? && @game.frames.last.is_spare?
      @hide_second_roll = true
    end
  end

  # GET /games/new
  def new
    @game  = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_frame
    new_frame_params = frame_params.merge({:game_id => params[:id]})
    if @game.extra_frame?
      new_frame_params.merge!({:extra_frame => true})
    end
    @frame = Frame.new(new_frame_params)
    if @frame.save
      redirect_to @game, notice: 'Frame was successfully created.'
    else
      render 'show'
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
       params.fetch(:game).permit(:name)
    end

    def frame_params
       params.fetch(:frame).permit(:first_roll, :second_roll)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_score.html.erb
<%= form_for @frame, :url => add_frame_game_path do |f| %>
  <% if @frame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@frame.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @frame.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :first_roll%>
  <%= f.text_field :first_roll %>
  <% unless @hide_second_roll %>
    <%= f.label :second_roll %>
    <%= f.text_field :second_roll %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_score_board.html.erb
<style>
  table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
  }
  th, td {
      padding: 5px;
  }
</style>
<h3> ScoreBoard</h3>
<hr>
<table>
<tr>
<% @game.frames.take(10).each_with_index do |frame, index|%>
<div>
<td>
Frame <%=index.succ%> |
  <table>
  <tr>
<% if frame.is_strike? %>
  <td><strong><%= 'X' %> </strong></td>
<% else %>
  <td><strong><%= frame.first_roll ? frame.first_roll : '0' %> </strong></td>
<% end %>
<% if frame.is_spare? %>
<td> <strong><%= '/'%> </strong> </td>
<% else %>
  <td><strong><%= frame.second_roll ? frame.second_roll : '0'%> </strong></td>
<% end %>
</tr>
</table>
Score: <strong><%= frame.score %></strong>
</td>
<div>
<% end %>
</tr>
</table>
<hr>
<br/> <br/> <br/>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/finished.html.erb
Contratulations, you completed the game.
<br/>
Your total score is <strong><%=@game.final_score?%></strong>
<br/>
<%= render 'score_board' %>
<%= link_to 'Start a New Game', new_game_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'score_board' %>
<%= render 'score' %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bowling</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>